/**
 * Copyright (C) 2014 Coinport Inc. <http://www.coinport.com>
 *
 * Persistent Events.
 */

package com.coinport.coinex.data

// Persistent Events. All events are generated by a certain processor and handeled by another processor.
// For each event, we'll comment it in the form of "origin -> handler".

// AccountProcessor -> MarketProcessor events
case class OrderSubmitted(market: MarketSide, order: Order) extends Evt

// MarketProcessor -> AccountProcessor events
case class OrderCancelled(side: MarketSide, order: Order) extends Evt
case class TransactionsCreated(txs: Seq[Transaction]) extends Evt
case class NewTxPriceSeen(side: MarketSide, price: Double) extends Evt