
/**
 * Copyright (C) 2014 Coinport Inc. <http://www.coinport.com>
 *
 * This file was auto generated by auto_gen_serializer.sh on Wed Apr 02 15:22:49 CST 2014
 */

package com.coinport.coinex.serializers

import akka.serialization.Serializer
import com.twitter.bijection.scrooge.BinaryScalaCodec
import com.coinport.coinex.data._

class ThriftBinarySerializer extends Serializer {
  val includeManifest: Boolean = true
  val identifier = 607870725
  lazy val s_0 = BinaryScalaCodec(UserProfile)
  lazy val s_1 = BinaryScalaCodec(MarketSide)
  lazy val s_2 = BinaryScalaCodec(Fee)
  lazy val s_3 = BinaryScalaCodec(Order)
  lazy val s_4 = BinaryScalaCodec(OrderInfo)
  lazy val s_5 = BinaryScalaCodec(OrderUpdate)
  lazy val s_6 = BinaryScalaCodec(Transaction)
  lazy val s_7 = BinaryScalaCodec(CashAccount)
  lazy val s_8 = BinaryScalaCodec(UserAccount)
  lazy val s_9 = BinaryScalaCodec(PersistentAccountState)
  lazy val s_10 = BinaryScalaCodec(UserLogsState)
  lazy val s_11 = BinaryScalaCodec(MarketDepthItem)
  lazy val s_12 = BinaryScalaCodec(MarketDepth)
  lazy val s_13 = BinaryScalaCodec(CandleDataItem)
  lazy val s_14 = BinaryScalaCodec(CandleData)
  lazy val s_15 = BinaryScalaCodec(MarketByMetrics)
  lazy val s_16 = BinaryScalaCodec(Metrics)
  lazy val s_17 = BinaryScalaCodec(TransactionItem)
  lazy val s_18 = BinaryScalaCodec(TransactionData)
  lazy val s_19 = BinaryScalaCodec(ApiSecret)
  lazy val s_20 = BinaryScalaCodec(ApiSecretState)
  lazy val s_21 = BinaryScalaCodec(Deposit)
  lazy val s_22 = BinaryScalaCodec(Withdrawal)
  lazy val s_23 = BinaryScalaCodec(AdminCommandResult)
  lazy val s_24 = BinaryScalaCodec(DoRegisterUser)
  lazy val s_25 = BinaryScalaCodec(RegisterUserFailed)
  lazy val s_26 = BinaryScalaCodec(RegisterUserSucceeded)
  lazy val s_27 = BinaryScalaCodec(DoRequestPasswordReset)
  lazy val s_28 = BinaryScalaCodec(RequestPasswordResetFailed)
  lazy val s_29 = BinaryScalaCodec(RequestPasswordResetSucceeded)
  lazy val s_30 = BinaryScalaCodec(DoResetPassword)
  lazy val s_31 = BinaryScalaCodec(ResetPasswordFailed)
  lazy val s_32 = BinaryScalaCodec(ResetPasswordSucceeded)
  lazy val s_33 = BinaryScalaCodec(Login)
  lazy val s_34 = BinaryScalaCodec(LoginFailed)
  lazy val s_35 = BinaryScalaCodec(LoginSucceeded)
  lazy val s_36 = BinaryScalaCodec(ValidatePasswordResetToken)
  lazy val s_37 = BinaryScalaCodec(PasswordResetTokenValidationResult)
  lazy val s_38 = BinaryScalaCodec(DoRequestCashDeposit)
  lazy val s_39 = BinaryScalaCodec(RequestCashDepositFailed)
  lazy val s_40 = BinaryScalaCodec(RequestCashDepositSucceeded)
  lazy val s_41 = BinaryScalaCodec(DoRequestCashWithdrawal)
  lazy val s_42 = BinaryScalaCodec(RequestCashWithdrawalFailed)
  lazy val s_43 = BinaryScalaCodec(RequestCashWithdrawalSucceeded)
  lazy val s_44 = BinaryScalaCodec(AdminConfirmCashDepositFailure)
  lazy val s_45 = BinaryScalaCodec(AdminConfirmCashDepositSuccess)
  lazy val s_46 = BinaryScalaCodec(AdminConfirmCashWithdrawalFailure)
  lazy val s_47 = BinaryScalaCodec(AdminConfirmCashWithdrawalSuccess)
  lazy val s_48 = BinaryScalaCodec(DoSubmitOrder)
  lazy val s_49 = BinaryScalaCodec(SubmitOrderFailed)
  lazy val s_50 = BinaryScalaCodec(OrderFundFrozen)
  lazy val s_51 = BinaryScalaCodec(DoAddNewApiSecret)
  lazy val s_52 = BinaryScalaCodec(DoDeleteApiSecret)
  lazy val s_53 = BinaryScalaCodec(ApiSecretOperationResult)
  lazy val s_54 = BinaryScalaCodec(QueryApiSecrets)
  lazy val s_55 = BinaryScalaCodec(QueryApiSecretsResult)
  lazy val s_56 = BinaryScalaCodec(DoCancelOrder)
  lazy val s_57 = BinaryScalaCodec(CancelOrderFailed)
  lazy val s_58 = BinaryScalaCodec(OrderSubmitted)
  lazy val s_59 = BinaryScalaCodec(OrderCancelled)
  lazy val s_60 = BinaryScalaCodec(DoUpdateMetrics)
  lazy val s_61 = BinaryScalaCodec(DoSendEmail)
  lazy val s_62 = BinaryScalaCodec(QueryAccount)
  lazy val s_63 = BinaryScalaCodec(QueryAccountResult)
  lazy val s_64 = BinaryScalaCodec(QueryMarketDepth)
  lazy val s_65 = BinaryScalaCodec(QueryMarketDepthResult)
  lazy val s_66 = BinaryScalaCodec(QueryCandleData)
  lazy val s_67 = BinaryScalaCodec(QueryCandleDataResult)
  lazy val s_68 = BinaryScalaCodec(QueryUserTransaction)
  lazy val s_69 = BinaryScalaCodec(QueryUserTransactionResult)
  lazy val s_70 = BinaryScalaCodec(QueryUserOrders)
  lazy val s_71 = BinaryScalaCodec(QueryUserOrdersResult)
  lazy val s_72 = BinaryScalaCodec(QueryTransactionData)
  lazy val s_73 = BinaryScalaCodec(QueryTransactionDataResult)
  lazy val s_74 = BinaryScalaCodec(QueryOrderData)
  lazy val s_75 = BinaryScalaCodec(QueryOrderDataResult)

  def toBinary(obj: AnyRef): Array[Byte] = obj match {
    case m: UserProfile => s_0(m)
    case m: MarketSide => s_1(m)
    case m: Fee => s_2(m)
    case m: Order => s_3(m)
    case m: OrderInfo => s_4(m)
    case m: OrderUpdate => s_5(m)
    case m: Transaction => s_6(m)
    case m: CashAccount => s_7(m)
    case m: UserAccount => s_8(m)
    case m: PersistentAccountState => s_9(m)
    case m: UserLogsState => s_10(m)
    case m: MarketDepthItem => s_11(m)
    case m: MarketDepth => s_12(m)
    case m: CandleDataItem => s_13(m)
    case m: CandleData => s_14(m)
    case m: MarketByMetrics => s_15(m)
    case m: Metrics => s_16(m)
    case m: TransactionItem => s_17(m)
    case m: TransactionData => s_18(m)
    case m: ApiSecret => s_19(m)
    case m: ApiSecretState => s_20(m)
    case m: Deposit => s_21(m)
    case m: Withdrawal => s_22(m)
    case m: AdminCommandResult => s_23(m)
    case m: DoRegisterUser => s_24(m)
    case m: RegisterUserFailed => s_25(m)
    case m: RegisterUserSucceeded => s_26(m)
    case m: DoRequestPasswordReset => s_27(m)
    case m: RequestPasswordResetFailed => s_28(m)
    case m: RequestPasswordResetSucceeded => s_29(m)
    case m: DoResetPassword => s_30(m)
    case m: ResetPasswordFailed => s_31(m)
    case m: ResetPasswordSucceeded => s_32(m)
    case m: Login => s_33(m)
    case m: LoginFailed => s_34(m)
    case m: LoginSucceeded => s_35(m)
    case m: ValidatePasswordResetToken => s_36(m)
    case m: PasswordResetTokenValidationResult => s_37(m)
    case m: DoRequestCashDeposit => s_38(m)
    case m: RequestCashDepositFailed => s_39(m)
    case m: RequestCashDepositSucceeded => s_40(m)
    case m: DoRequestCashWithdrawal => s_41(m)
    case m: RequestCashWithdrawalFailed => s_42(m)
    case m: RequestCashWithdrawalSucceeded => s_43(m)
    case m: AdminConfirmCashDepositFailure => s_44(m)
    case m: AdminConfirmCashDepositSuccess => s_45(m)
    case m: AdminConfirmCashWithdrawalFailure => s_46(m)
    case m: AdminConfirmCashWithdrawalSuccess => s_47(m)
    case m: DoSubmitOrder => s_48(m)
    case m: SubmitOrderFailed => s_49(m)
    case m: OrderFundFrozen => s_50(m)
    case m: DoAddNewApiSecret => s_51(m)
    case m: DoDeleteApiSecret => s_52(m)
    case m: ApiSecretOperationResult => s_53(m)
    case m: QueryApiSecrets => s_54(m)
    case m: QueryApiSecretsResult => s_55(m)
    case m: DoCancelOrder => s_56(m)
    case m: CancelOrderFailed => s_57(m)
    case m: OrderSubmitted => s_58(m)
    case m: OrderCancelled => s_59(m)
    case m: DoUpdateMetrics => s_60(m)
    case m: DoSendEmail => s_61(m)
    case m: QueryAccount => s_62(m)
    case m: QueryAccountResult => s_63(m)
    case m: QueryMarketDepth => s_64(m)
    case m: QueryMarketDepthResult => s_65(m)
    case m: QueryCandleData => s_66(m)
    case m: QueryCandleDataResult => s_67(m)
    case m: QueryUserTransaction => s_68(m)
    case m: QueryUserTransactionResult => s_69(m)
    case m: QueryUserOrders => s_70(m)
    case m: QueryUserOrdersResult => s_71(m)
    case m: QueryTransactionData => s_72(m)
    case m: QueryTransactionDataResult => s_73(m)
    case m: QueryOrderData => s_74(m)
    case m: QueryOrderDataResult => s_75(m)

    case m => throw new IllegalArgumentException("Cannot serialize object: " + m)
  }

  def fromBinary(bytes: Array[Byte],
    clazz: Option[Class[_]]): AnyRef = clazz match {
    case Some(c) if c == classOf[UserProfile.Immutable] => s_0.invert(bytes).get
    case Some(c) if c == classOf[MarketSide.Immutable] => s_1.invert(bytes).get
    case Some(c) if c == classOf[Fee.Immutable] => s_2.invert(bytes).get
    case Some(c) if c == classOf[Order.Immutable] => s_3.invert(bytes).get
    case Some(c) if c == classOf[OrderInfo.Immutable] => s_4.invert(bytes).get
    case Some(c) if c == classOf[OrderUpdate.Immutable] => s_5.invert(bytes).get
    case Some(c) if c == classOf[Transaction.Immutable] => s_6.invert(bytes).get
    case Some(c) if c == classOf[CashAccount.Immutable] => s_7.invert(bytes).get
    case Some(c) if c == classOf[UserAccount.Immutable] => s_8.invert(bytes).get
    case Some(c) if c == classOf[PersistentAccountState.Immutable] => s_9.invert(bytes).get
    case Some(c) if c == classOf[UserLogsState.Immutable] => s_10.invert(bytes).get
    case Some(c) if c == classOf[MarketDepthItem.Immutable] => s_11.invert(bytes).get
    case Some(c) if c == classOf[MarketDepth.Immutable] => s_12.invert(bytes).get
    case Some(c) if c == classOf[CandleDataItem.Immutable] => s_13.invert(bytes).get
    case Some(c) if c == classOf[CandleData.Immutable] => s_14.invert(bytes).get
    case Some(c) if c == classOf[MarketByMetrics.Immutable] => s_15.invert(bytes).get
    case Some(c) if c == classOf[Metrics.Immutable] => s_16.invert(bytes).get
    case Some(c) if c == classOf[TransactionItem.Immutable] => s_17.invert(bytes).get
    case Some(c) if c == classOf[TransactionData.Immutable] => s_18.invert(bytes).get
    case Some(c) if c == classOf[ApiSecret.Immutable] => s_19.invert(bytes).get
    case Some(c) if c == classOf[ApiSecretState.Immutable] => s_20.invert(bytes).get
    case Some(c) if c == classOf[Deposit.Immutable] => s_21.invert(bytes).get
    case Some(c) if c == classOf[Withdrawal.Immutable] => s_22.invert(bytes).get
    case Some(c) if c == classOf[AdminCommandResult.Immutable] => s_23.invert(bytes).get
    case Some(c) if c == classOf[DoRegisterUser.Immutable] => s_24.invert(bytes).get
    case Some(c) if c == classOf[RegisterUserFailed.Immutable] => s_25.invert(bytes).get
    case Some(c) if c == classOf[RegisterUserSucceeded.Immutable] => s_26.invert(bytes).get
    case Some(c) if c == classOf[DoRequestPasswordReset.Immutable] => s_27.invert(bytes).get
    case Some(c) if c == classOf[RequestPasswordResetFailed.Immutable] => s_28.invert(bytes).get
    case Some(c) if c == classOf[RequestPasswordResetSucceeded.Immutable] => s_29.invert(bytes).get
    case Some(c) if c == classOf[DoResetPassword.Immutable] => s_30.invert(bytes).get
    case Some(c) if c == classOf[ResetPasswordFailed.Immutable] => s_31.invert(bytes).get
    case Some(c) if c == classOf[ResetPasswordSucceeded.Immutable] => s_32.invert(bytes).get
    case Some(c) if c == classOf[Login.Immutable] => s_33.invert(bytes).get
    case Some(c) if c == classOf[LoginFailed.Immutable] => s_34.invert(bytes).get
    case Some(c) if c == classOf[LoginSucceeded.Immutable] => s_35.invert(bytes).get
    case Some(c) if c == classOf[ValidatePasswordResetToken.Immutable] => s_36.invert(bytes).get
    case Some(c) if c == classOf[PasswordResetTokenValidationResult.Immutable] => s_37.invert(bytes).get
    case Some(c) if c == classOf[DoRequestCashDeposit.Immutable] => s_38.invert(bytes).get
    case Some(c) if c == classOf[RequestCashDepositFailed.Immutable] => s_39.invert(bytes).get
    case Some(c) if c == classOf[RequestCashDepositSucceeded.Immutable] => s_40.invert(bytes).get
    case Some(c) if c == classOf[DoRequestCashWithdrawal.Immutable] => s_41.invert(bytes).get
    case Some(c) if c == classOf[RequestCashWithdrawalFailed.Immutable] => s_42.invert(bytes).get
    case Some(c) if c == classOf[RequestCashWithdrawalSucceeded.Immutable] => s_43.invert(bytes).get
    case Some(c) if c == classOf[AdminConfirmCashDepositFailure.Immutable] => s_44.invert(bytes).get
    case Some(c) if c == classOf[AdminConfirmCashDepositSuccess.Immutable] => s_45.invert(bytes).get
    case Some(c) if c == classOf[AdminConfirmCashWithdrawalFailure.Immutable] => s_46.invert(bytes).get
    case Some(c) if c == classOf[AdminConfirmCashWithdrawalSuccess.Immutable] => s_47.invert(bytes).get
    case Some(c) if c == classOf[DoSubmitOrder.Immutable] => s_48.invert(bytes).get
    case Some(c) if c == classOf[SubmitOrderFailed.Immutable] => s_49.invert(bytes).get
    case Some(c) if c == classOf[OrderFundFrozen.Immutable] => s_50.invert(bytes).get
    case Some(c) if c == classOf[DoAddNewApiSecret.Immutable] => s_51.invert(bytes).get
    case Some(c) if c == classOf[DoDeleteApiSecret.Immutable] => s_52.invert(bytes).get
    case Some(c) if c == classOf[ApiSecretOperationResult.Immutable] => s_53.invert(bytes).get
    case Some(c) if c == classOf[QueryApiSecrets.Immutable] => s_54.invert(bytes).get
    case Some(c) if c == classOf[QueryApiSecretsResult.Immutable] => s_55.invert(bytes).get
    case Some(c) if c == classOf[DoCancelOrder.Immutable] => s_56.invert(bytes).get
    case Some(c) if c == classOf[CancelOrderFailed.Immutable] => s_57.invert(bytes).get
    case Some(c) if c == classOf[OrderSubmitted.Immutable] => s_58.invert(bytes).get
    case Some(c) if c == classOf[OrderCancelled.Immutable] => s_59.invert(bytes).get
    case Some(c) if c == classOf[DoUpdateMetrics.Immutable] => s_60.invert(bytes).get
    case Some(c) if c == classOf[DoSendEmail.Immutable] => s_61.invert(bytes).get
    case Some(c) if c == classOf[QueryAccount.Immutable] => s_62.invert(bytes).get
    case Some(c) if c == classOf[QueryAccountResult.Immutable] => s_63.invert(bytes).get
    case Some(c) if c == classOf[QueryMarketDepth.Immutable] => s_64.invert(bytes).get
    case Some(c) if c == classOf[QueryMarketDepthResult.Immutable] => s_65.invert(bytes).get
    case Some(c) if c == classOf[QueryCandleData.Immutable] => s_66.invert(bytes).get
    case Some(c) if c == classOf[QueryCandleDataResult.Immutable] => s_67.invert(bytes).get
    case Some(c) if c == classOf[QueryUserTransaction.Immutable] => s_68.invert(bytes).get
    case Some(c) if c == classOf[QueryUserTransactionResult.Immutable] => s_69.invert(bytes).get
    case Some(c) if c == classOf[QueryUserOrders.Immutable] => s_70.invert(bytes).get
    case Some(c) if c == classOf[QueryUserOrdersResult.Immutable] => s_71.invert(bytes).get
    case Some(c) if c == classOf[QueryTransactionData.Immutable] => s_72.invert(bytes).get
    case Some(c) if c == classOf[QueryTransactionDataResult.Immutable] => s_73.invert(bytes).get
    case Some(c) if c == classOf[QueryOrderData.Immutable] => s_74.invert(bytes).get
    case Some(c) if c == classOf[QueryOrderDataResult.Immutable] => s_75.invert(bytes).get

    case Some(c) => throw new IllegalArgumentException("Cannot deserialize class: " + c.getCanonicalName)
    case None => throw new IllegalArgumentException("No class found in EventSerializer when deserializing array: " + bytes.mkString("").take(100))
  }
}
